dataset_0 = [
	"ACCAGCGGGTTGCCGACGTAGCAGATA",
	"GCACTGTTGTTCCACGCATAGACA",
	"ACACCGTGGGTTCTCGACGGAGTGACA",
	"ACGAGGTGGGCGTTCCGACCAGGGAGGCC",
	"TACGGGGGTTTCCGACGAGCAGACA"
]

dataset_1 = [
	"TACAGCTCCCCACGGGCGGGGCC",
	"CACTAGTCTCCCCACCGACGCGGGCCT",
	"GTACAGGCTCCCCATACGCGGGGCCT",
	"CCCAGCTCGCCCACGAAGTGTGTGCCT",
	"CCCAGTCTCCCCATGAAGCGGGGCC"
]

dataset_2 = [
	"GCAACTAATCCCTGGCCGATGGTTAC",
	"TCAACTAATCGGCCTATGTCGGGATATTTATT",
	"TCAACTGGTCCCCCATCGCTGTATTTCCT",
	"TCAACTATTCCCATGGCTGATTTTGACT",
	"TCAACCTAATCCCTAGGGCGATATTTACT"
]

dataset_3 = [
	"CACGTGGGCCGATCTAGAGACCGGTGGGGGGG",
	"ACGACGGCATCTAGAGACCGGTGATGGG",
	"CACGAGGATCTAGAGACGCGGTGATGTG",
	"CACGAGGCGATCTAGAACCGGTGATGTG",
	"CACGAGGCGATCTGAGGCCGGTGATGGT"
]

dataset_4 = [
	"TGAGCCTTTGTTCGCGCTCCGGATGT",
	"TGACCCGTTTCTCTCGCTCCGGATGT",
	"CGACCGTTGTCTCGCGCTCGGGTTGT",
	"GGACCGCTGTCTCGCGCTCCGTGTTGT",
	"TGACCGTTGTCTGGGGCTCCGATGT"
]

dataset_5 = [
	"CCTCCGCGACTCACCCGCTGTTGGACG",
	"ACTCCGCCACCACCTCCGCGCTCGCTCG",
	"ACTCCGCGACCACCCCCGCTCTCGGCG",
	"ACTGCGCGACGACCTCCGCTCTCGCCG",
	"ACTTCGCGACTCACCTTTGCTCTCTACG"
]

dataset_6 = [
	"TTTCCCTTTTCCACGTGGACCTGTA",
	"TTTCCCTTTTCACGTATCTGTA",
	"TTTCCCTTTTCACGTTACTTA",
	"TTTGCCTTTTTCACGGTACTGTA",
	"CTTCCTTTTTTACGTTACTGTCA"
]

dataset_7 = [
	"CGTCCCAGTTGGTCTGCATGATGT",
	"CGTCCCATTGGTCTGCATTTATCCGC",
	"TCCCATTGCTCTGCATTATCGT",
	"CTGTCCCATTGTGTGCATGTATCGT",
	"GGTCCCATTTGTCGTGCGTTTCT"
]

dataset_8 = [
	"GTACTCCTCGATATATACCGGA",
	"GTACTCCTGATATTAGCGA",
	"GTACTCCTGATATTTACGA",
	"GTACTCGTGATACATACCGA",
	"GTCCTCCCTGATATATACCGA"
]

dataset_9 = [
	"GACGAGACTGGCATTATTCCTCGAA",
	"GACGAGACCGGCAATATTCCTCGAA",
	"GACGAGACCGGCAATATTCCTCCAA",
	"GACGAGACCGGTAATATTCCTCGCCA",
	"GGCGAGACCGGAATATTTCTCTCGTA"
]

dataset_10 = [
	"GTGGTGAGGGTTAAAACAGTG",
	"GTGGCGAGGGTTAAGACAGTG",
	"GTGGCGAGGGTTAAAACAGTG",
	"GTGGCGAGGGTTCAAAACAGTG",
	"GTGGCCAGCGGTTAATACTGTG"
]

dataset_11 = [
	"GGGGGGTAATCAGTGTGGAAGATCGATT",
	"GTGAGTTAATCAGTGTGGAAATCCGATT",
	"TGTGGAGGTATCAGTCTGGGATATCCGAT",
	"CGTGAGGGTAATCATGTGGATAGATCCGATT",
	"GTGAGGTAATCAGTGTGGAAGCCCTAT"
]

dataset_12 = [
	"ATAAGGCCATTGGGTTGACCGCTACCCGG",
	"ATTAGGCCACGCTTGAACCTCCACCCCG",
	"ATCAGGCCGGTTTAACCTCTGACGCCG",
	"ATAAGGCGCATTGGTCTAGACCCGCTACCGCCG",
	"AACGCCCATTGGTTTAATCGCTCCCCCG"
]

dataset_13 = [
	"AATAGCCGAGAGCCTTGGAG",
	"AATGATGCCGGGCATGGAG",
	"GGATGAGCCGAGAGCATGGG",
	"AATGATCCGAGAGCATTAG",
	"TATTAGTTGCGAGCTTGGAG"
]

dataset_14 = [
	"CACTGACTGCTCGGTCTTCGGACAAGGA",
	"CACTGACTGCTGGTCCTTCGGACAAGA",
	"CACTGACTGCTCGTTCCTTCGGACAGA",
	"CACTGACTGCGCGGTCTTTCGGACACA",
	"GCCACTGACTGTCGGTCCTTCGGACAAGA"
]

dataset_15 = [
	"AATGGTAAAATAGAGAACCACC",
	"AAAGGATAAAATTTGATTACACC",
	"AAACTATAAATAGATAACACC",
	"AAAGGATAAAATAGATACC",
	"GAATGATAAATAGAGAACCCG"
]

dataset_16 = [
	"AAGGATGGCCCTCACCTTAGTC",
	"TAGTATGGCCTTCACCTTAGTC",
	"AAGGAGGCCTCAGCTATTC",
	"GTAGGATGGCCCAGCTTAGTC",
	"TAGGATGCGACCTAGTC"
]

dataset_17 = [
	"CATAGGTCATGGGTTTCTATAGACCGGTTC",
	"CAGTAGGTACTGGCTTTCAGTAGAACGGCTCC",
	"CATTAGTAGGGTTTCAGTAGAACGGTCC",
	"CTTAGGTTCGGGTTGCACTAGAACGGTCC",
	"CATTAGGTATGGGTTTCAATAGGACGGCTGC"
]

dataset_18 = [
	"TCCCTGTGTTCCGCGCGCATAGTTTTTCTA",
	"TCCCTCGTCCGCCGCGGATAGTTTCTAA",
	"TCGCCTCCCGCCGCGGATATTTTCAA",
	"GCGCCCGGCCGCCGGCGGATGAGTTTTCAA",
	"CTCCCCGTCCGCCCGCGTATATGTCAA"
]

dataset_19 = [
	"ATAACGTCGGAGGAGACGAATCGTTTC",
	"ATAACGTCGATGCTGGACCGACTGGCGTTC",
	"ATTAACGAGGATGTCCAATCGTGCGTTC",
	"GATAACGTAGGATGTGGTCTGAAGGGCTTC",
	"ATCAACCTAGGATGCTAGATCGAATCGCTGC"
]

dataset_20 = [
	"CGCTATGCCTGATGGCATAGTCCACCT",
	"GCCTGGGCCTTATCCATTATCCATCT",
	"GCGTGCTCCTAATCCCTAGTCCATCT",
	"GCAGTGCTCCTATCCAAGGCCACCT",
	"GCATGCCCAATGTTTGTCCACCT"
]

dataset_21 = [
	"AAGTAAGCAATCTTGGAGCCTGCCCTT",
	"AAGTAAGCAAGTTTTGTACGGGCCTGCGTTT",
	"ATGTAGCAATAGTGGACCCCGCCTTT",
	"AAGTAAGCAATATTGGACGCCTGCTTT",
	"AAGTAAGAATGATTGGGACGCCTTCGCTTT"
]

dataset_22 = [
	"GCTGGTCCTTCGCAACTTGGGCTATGATT",
	"GCTGCTCGCGTCGAAACTTTGACTATGTTT",
	"GCTGATACGTCCGAACTTTGCCTATGATT",
	"GCTGATACGTCGGTACTTTGGCTATGATCT",
	"GCTGATACGTCGAAACTTTGACTATGATT"
]

dataset_23 = [
	"AGGAAATTGGTCCACCGCGCTTTTTGGGTT",
	"AGGAAAATGGCCACCGCGCTTTTTGGTT",
	"CGGAAATTGGCCACCGCGCTTTGTTT",
	"TGCAAAATGTCCATCCTTTGGTG",
	"GAGGAAAGATGGCCACGGCGCTTGTT"
]

dataset_24 = [
	"GGCTGCGACCCGAACGCCTGTAA",
	"TGACTGAGAGCTGACGCCGTAA",
	"TGTTTTGAGACTATCGCCTAA",
	"CGACTGCGACCTGTAACTCCGGAA",
	"TGGCTGAGACCTGAACGCGGTAA"
]

dataset_25 = [
	"GGTTCTAGAATCTCTTCCTGCA",
	"GGTTCTAGAATTGGTCTTCCTCCA",
	"GGCTGTCGTAGAATGGCTCTTCCTCCA",
	"GGTTCTAGCTAACGGCTGCTTCCCTGCA",
	"GGTTCTAGGAATGGCTCTTCCTGCA"
]

dataset_26 = [
	"GATGTGATCAAAGCCATTGGCCGGGA",
	"GAAGGTGGTCCACGCCACGTGCTGTGTAA",
	"CAAGGTGATCAAAGCCACGTTCCGTGAA",
	"GAAGGTGACTCGGAGCCACGTCGGCGTGAT",
	"GAAGGTGTATCAAAGGGACGTGCCTTGAC"
]

dataset_27 = [
	"TAACATCGTTATCTAGTGTTCAAT",
	"TGCGACAACGGAGCTAGTGTTCGAA",
	"TGAGACTAACGGCTAGTGTGCAT",
	"CTGAGACATCGGAGCTAGTGCTTCAAT",
	"TGAGAGAATCGGAGCGCAGTGTTTAAT"
]

dataset_28 = [
	"ACCCAGCAGGGCGTGCTGTTCGCATG",
	"AGCCAGCAGGCGACTCCCCAG",
	"ACCCAGGAGGCGACTGTTCTCATG",
	"GGCTCAGCAGGCGACTGTTCGTATG",
	"ACCCAGCAGGGACCTGTTCGCATT"
]

dataset_29 = [
	"GAGCGAGGATTCTATGTGCTGGG",
	"GAGCGTAGGATTCTTGTCCTCGGG",
	"GAGCCTGGATTGCTCTGTGCTGGG",
	"GAGCGAGGATCTTAGTGCTGGG",
	"GAGCGATGATTCTATGTGCTGGG"
]

dataset_30 = [
	"GTTACTTTCTTCTGGGATCAGAGTAATG",
	"GTTAATCTCGTTCTAGGGATCAGAAGTCATG",
	"GTTAATGCCTTCTATGGAGTCAGAAGTAATTG",
	"GCAATGCCTTCTAGGGATCCCGAAGTAACG",
	"GTTAATGCTTCTCGGGTCAGAAGTACGTG"
]

dataset_31 = [
	"CGACGTCGCAGAATATCAGAAGGTTTT",
	"CGTCTCTGATATATCGATGGTTT",
	"CACGTCGGGGAATTCTTGGAGGTTT",
	"CGGGGCGGGATGATCAGAGGGTTT",
	"CGACGTCGGAGATGCTCAGAAGGTTT"
]

dataset_32 = [
	"AGAAGATTGCCTTGCTGTAACGG",
	"AGAACATGCTTGCTGTAACGG",
	"AGAATATGCCTGCTGTAACCGG",
	"AGAATATTCTGCTGTAACGG",
	"AGAATATCCCTGTACCG"
]

dataset_33 = [
	"ACTGAGCCATTCTCTCATGCCCGC",
	"ACGAGCCAGCTTCATGACAGC",
	"ACCGGGCCATCTCTATGACAGC",
	"GCGCAGCCATCTCGCATGCCAGC",
	"CGGCAGCCATCTCGCATGACGGC"
]

dataset_34 = [
	"GTTTTAGTGGTCGACGGCCGCAGGTGCGCC",
	"GGTTATGGGCCACGGGCGCTATGGCGTCA",
	"GTTCATGGGCCACGGCCGAGGGGCGTTCCA",
	"GTTTTTGGTCGACGGCTTGCAGGGCGTCCA",
	"GTTTTATGTCGGACGGGCGGCAGGTCGTCCA"
]

dataset_35 = [
	"ACGCGTTCTACCATGTGTACCGC",
	"TAAGCGTCTATCATGTGATCCGC",
	"AACCTTTCTACCATGTGTATCCGC",
	"AACTTTCTACCTATGGGTATTCGC",
	"AAGCTTTCTACCATGGGTATCCGC"
]

dataset_36 = [
	"CTCAAAGCGTGCTGGTACTTCTCGCGGCCG",
	"CTCAACGCGGGCTGGTATTCTCGCGGCCA",
	"CCTCGAAGCGGGGCTGGTCTTCTCGCGGGCA",
	"GTCAAAGCGGGGCTGCTATTCTCGCGGCCA",
	"CTCGGAGGGGGCGTGGGATTCTCGGCGGCCA"
]

dataset_37 = [
	"ACTACCCCACCGCCCTCGATTA",
	"ACTGCTCCCCAGCTCCCGCTCGCGATGA",
	"TACCCCTGCCCCTCTCGCCGATTA",
	"ACTACCCCAGCCCTCTCGGCGATTA",
	"ACTCCCAGCCCCCTCTCGCGATTGA"
]

dataset_38 = [
	"GGGCCATTCAGGGAGGCACGGCAAACGTTT",
	"GGGTTTCACGATGCACCGCGAAACGTA",
	"GGGCATTAGGAGGCACGGAACACGTAT",
	"GGGCATTCAGCGAGGCACGGTAAACGTAT",
	"GGGCTTTAGGAGGCACCGGAGAACCTAT"
]

dataset_39 = [
	"GCTAGGAATATGCTACC",
	"GCCCGGAATATTATCACGC",
	"TGTGAGGATATATTGATCCGC",
	"GCTAGGAATATTGATCACGC",
	"GCTAGGAACATTGATCACGC"
]

dataset_40 = [
	"AACCGACACTTGCGATCTATTCTTGACG",
	"CAACGACACGTTGCATTATCTCTGACG",
	"CTAACCGACCGTTGTCATGTATTCTTGTCG",
	"CAACCTACACCGTTGCATTCTATTCTTACG",
	"GTATCCGACACTTGCATGTATTTTGACG"
]

dataset_41 = [
	"AACTCGTCCTAGACAACGCGCCTAAACCGT",
	"AACTCTGTCTAGACACAGCGCCTAAAGC",
	"AACTCGTCCTAGGCCACACTGCGTAATAGCT",
	"AACTCGTCTCAGACACACCGCGGATAAGCT",
	"ACCGCGGCTACACACACCGCCGTAAAGCTT"
]

dataset_42 = [
	"GTTCAGGTGTATTGCGGCTACTCC",
	"GTTCAGGCTATTGAGGAAATTCC",
	"TTTCAGTGCGTCGGGAGGGAAGTCC",
	"GTTCAGGCTCTTGTGGAAACCC",
	"GTTCAGGCTATTTGATCAAACTCC"
]

dataset_43 = [
	"CTACTCTCGGTACTGATACCGATCGCGGG",
	"CTATCCGGTAGTCATCAAGATCCCTTG",
	"CTATCTCGGCACTTCATAAGTTCCGTG",
	"CTTCTTTGTACTCATAAGATCCTTG",
	"CTGTCTCGGTACTCATTATATTTCCTTG"
]

dataset_44 = [
	"GCCAAACGAAGACAATGGGTA",
	"GGCCAAAGACAGACAATGGCGTT",
	"CGCCAAAAGAATAAGTGTGCTA",
	"GGCCAAAGAGAATACAACGGCTA",
	"GGCCACAAAGAATACAATGGCTTG"
]

dataset_45 = [
	"ACTCACTAATCTCGACGACACAACCTA",
	"ACTACTATTGTCGAGATCAACTCA",
	"TACTACTAATCTCGACGACACAACTCA",
	"ATACTATCTCGACGACACATACTCA",
	"GCCTGCGCTAATCCGACGACACAACTCA"
]

dataset_46 = [
	"GTAGGGGGTACTTCAGTCATAG",
	"TGTCGGGGGTACCTAGTCATAG",
	"GGAGGGTGTACTTCAGTCAAG",
	"GTAGGGGGTACTTCAGTCATAG",
	"CTAGGGGGTACCTCAGTCATAG"
]

dataset_47 = [
	"GTTGTATGAGAGGGGGCTGAT",
	"GTGTACGTTGATGGTATGAT",
	"GTGTACGAGGTGGGGACGAT",
	"GTGTACGAGATGGGATGAGT",
	"GTGTACGAGATCGGGATGAT"
]

dataset_48 = [
	"TCTTTCACCTCACGATCGGCTGTAC",
	"TGTTTCACGTCACGATCTGCTGTAC",
	"TGTTTCACGTCACGATCTGCGAC",
	"TGTTTCCCGTCACGATCTCGCTGTAC",
	"TGTTTCACGTCTACGTATCTGCTGTAC"
]

dataset_49 = [
	"GGCCGGAGTCGCCTGCAGTACCTG",
	"GGACGGAGTCGCCTGCAGTACCT",
	"GGCCGAGTCGTCCTGCAGTACCTGG",
	"GGTCGATGTCGCCTGCAGTACCTG",
	"GACGATCCCCTCGCAGTACCTG"
]

datasets = [
	"dataset_0",
	"dataset_1",
	"dataset_2",
	"dataset_3",
	"dataset_4",
	"dataset_5",
	"dataset_6",
	"dataset_7",
	"dataset_8",
	"dataset_9",
	"dataset_10",
	"dataset_11",
	"dataset_12",
	"dataset_13",
	"dataset_14",
	"dataset_15",
	"dataset_16",
	"dataset_17",
	"dataset_18",
	"dataset_19",
	"dataset_20",
	"dataset_21",
	"dataset_22",
	"dataset_23",
	"dataset_24",
	"dataset_25",
	"dataset_26",
	"dataset_27",
	"dataset_28",
	"dataset_29",
	"dataset_30",
	"dataset_31",
	"dataset_32",
	"dataset_33",
	"dataset_34",
	"dataset_35",
	"dataset_36",
	"dataset_37",
	"dataset_38",
	"dataset_39",
	"dataset_40",
	"dataset_41",
	"dataset_42",
	"dataset_43",
	"dataset_44",
	"dataset_45",
	"dataset_46",
	"dataset_47",
	"dataset_48",
	"dataset_49",
]

file_name = "dataset5"
